create table if not exists public.campusforma_courses (
  id text primary key,
  title text not null,
  description text not null,
  category text not null,
  subcategory text not null default '',
  duration text not null,
  lessons integer not null default 0 check (lessons >= 0),
  level text not null,
  price integer not null check (price >= 0),
  image text not null,
  instructor text not null,
  tag text,
  certification boolean not null default true,
  platform_url text not null default '/formations',
  is_active boolean not null default true,
  position integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.campusforma_orders (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  status text not null default 'pending' check (status in ('pending', 'paid', 'failed', 'refunded')),
  payment_method text not null check (payment_method in ('wave', 'orange_money', 'free_money')),
  customer_phone text not null,
  total_amount integer not null check (total_amount >= 0),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.campusforma_order_items (
  id bigint generated by default as identity primary key,
  order_id uuid not null references public.campusforma_orders(id) on delete cascade,
  course_id text not null references public.campusforma_courses(id) on delete restrict,
  title_snapshot text not null,
  price integer not null check (price >= 0),
  created_at timestamptz not null default now(),
  unique (order_id, course_id)
);

create table if not exists public.campusforma_newsletter_subscribers (
  id bigint generated by default as identity primary key,
  email text not null,
  created_at timestamptz not null default now()
);

create unique index if not exists campusforma_newsletter_email_unique
  on public.campusforma_newsletter_subscribers (lower(email));
create index if not exists campusforma_orders_user_created_idx
  on public.campusforma_orders (user_id, created_at desc);
create index if not exists campusforma_order_items_order_idx
  on public.campusforma_order_items (order_id);

alter table public.campusforma_courses enable row level security;
alter table public.campusforma_orders enable row level security;
alter table public.campusforma_order_items enable row level security;
alter table public.campusforma_newsletter_subscribers enable row level security;

drop policy if exists campusforma_courses_public_read on public.campusforma_courses;
create policy campusforma_courses_public_read
  on public.campusforma_courses for select
  to anon, authenticated
  using (is_active = true);

drop policy if exists campusforma_orders_owner_read on public.campusforma_orders;
create policy campusforma_orders_owner_read
  on public.campusforma_orders for select
  to authenticated
  using ((select auth.uid()) = user_id);

drop policy if exists campusforma_order_items_owner_read on public.campusforma_order_items;
create policy campusforma_order_items_owner_read
  on public.campusforma_order_items for select
  to authenticated
  using (
    exists (
      select 1 from public.campusforma_orders orders
      where orders.id = order_id and orders.user_id = (select auth.uid())
    )
  );

revoke all on table public.campusforma_courses from anon, authenticated;
revoke all on table public.campusforma_orders from anon, authenticated;
revoke all on table public.campusforma_order_items from anon, authenticated;
revoke all on table public.campusforma_newsletter_subscribers from anon, authenticated;
grant select on table public.campusforma_courses to anon, authenticated;
grant select on table public.campusforma_orders to authenticated;
grant select on table public.campusforma_order_items to authenticated;

create or replace function public.campusforma_create_order(
  course_ids text[],
  selected_payment_method text,
  customer_phone text
)
returns uuid
language plpgsql
security definer
set search_path = ''
as $$
declare
  current_user_id uuid := auth.uid();
  new_order_id uuid;
  computed_total integer;
  valid_course_count integer;
begin
  if current_user_id is null then
    raise exception 'Authentication required' using errcode = '42501';
  end if;
  if coalesce(cardinality(course_ids), 0) = 0 or cardinality(course_ids) > 25 then
    raise exception 'Invalid course selection';
  end if;
  if selected_payment_method not in ('wave', 'orange_money', 'free_money') then
    raise exception 'Invalid payment method';
  end if;
  if customer_phone !~ '^[+0-9 ()-]{8,25}$' then
    raise exception 'Invalid phone number';
  end if;

  select count(*), coalesce(sum(price), 0)::integer
    into valid_course_count, computed_total
  from public.campusforma_courses
  where id = any(course_ids) and is_active = true;

  if valid_course_count <> cardinality(course_ids) then
    raise exception 'One or more courses are unavailable';
  end if;

  insert into public.campusforma_orders (user_id, payment_method, customer_phone, total_amount)
  values (current_user_id, selected_payment_method, customer_phone, computed_total)
  returning id into new_order_id;

  insert into public.campusforma_order_items (order_id, course_id, title_snapshot, price)
  select new_order_id, id, title, price
  from public.campusforma_courses
  where id = any(course_ids) and is_active = true;

  return new_order_id;
end;
$$;

revoke all on function public.campusforma_create_order(text[], text, text) from public, anon, authenticated;
grant execute on function public.campusforma_create_order(text[], text, text) to authenticated;

create or replace function public.campusforma_subscribe_newsletter(subscriber_email text)
returns boolean
language plpgsql
security definer
set search_path = ''
as $$
declare
  normalized_email text := lower(trim(subscriber_email));
begin
  if length(normalized_email) > 320 or normalized_email !~ '^[^[:space:]@]+@[^[:space:]@]+\.[^[:space:]@]+$' then
    raise exception 'Invalid email address';
  end if;
  insert into public.campusforma_newsletter_subscribers (email)
  values (normalized_email)
  on conflict do nothing;
  return true;
end;
$$;

revoke all on function public.campusforma_subscribe_newsletter(text) from public, anon, authenticated;
grant execute on function public.campusforma_subscribe_newsletter(text) to anon, authenticated;
